version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run: 
          name: Build docker container
          command: docker build -t "normanrz/elevation-service:${CIRLCE_BUILD_NUM}" .

      - run: 
          name: Run unit tests
          command: |
            docker run \
              --rm \
              "normanrz/elevation-service:${CIRLCE_BUILD_NUM}" \
              yarn test

      - run: 
          name: Run S3 tests
          command: |
            docker run \
              --rm \
              -d \
              -eTILE_SET_PATH=s3:// \
              -p3000:3000 \
              --name elevation \
              "normanrz/elevation-service:${CIRLCE_BUILD_NUM}"
            sleep 5
            curl \
              -d '[[51.3, 13.4], [51.4, 13.3]]' \
              -XPOST \
              -H 'Content-Type: application/json' \
              http://localhost:3000
            docker stop elevation

      - run: 
          name: Run local tests
          command: |
            mkdir -p data/N51
            aws s3 cp s3://elevation-tiles-prod/skadi/N51/N51E013.hgt.gz data/N51
            docker run \
              --rm \
              -d \
              -p3000:3000 \
              --name elevation \
              -v$(pwd)/data:/app/data \
              "normanrz/elevation-service:${CIRLCE_BUILD_NUM}"
            sleep 5
            curl \
              -d '[[51.3, 13.4], [51.4, 13.3]]' \
              -XPOST \
              -H 'Content-Type: application/json' \
              http://localhost:3000
            docker stop elevation

        - run:
            name: Push Docker images
            command: |
              echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
              docker tag \
                "normanrz/elevation-service:${CIRLCE_BUILD_NUM}" \
                "normanrz/elevation-service:${CIRLCE_BRANCH}"
              docker push "normanrz/elevation-service:${CIRLCE_BUILD_NUM}"
              docker push "normanrz/elevation-service:${CIRLCE_BRANCH}"
              docker push "normanrz/elevation-service:latest"
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker tag \
                  "normanrz/elevation-service:${CIRLCE_BUILD_NUM}" \
                  "normanrz/elevation-service:latest"
                docker push "normanrz/elevation-service:latest"
              fi
              docker logout

workflows:
  version: 2
  default:
    jobs:
      - build
